import type {
  BookingField,
  BookingTab,
  Certification,
  FleetCategory,
  FleetVehicle,
  FooterColumn,
  FormField,
  HowItWorksStep,
  NavLink,
  ServiceItem,
  SocialLink,
  Stat,
  TeamMember,
  Testimonial,
  TrustPill,
  Value,
} from "@/types";

const vehicleImage =
  "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=80";
const suvImage =
  "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80";
const sprinterImage =
  "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1200&q=80";
const cityImage =
  "https://images.unsplash.com/photo-1537498425277-c283d32ef9db?auto=format&fit=crop&w=1400&q=80";

export const SITE_CONFIG = {
  meta: {
    siteName: "Luxy Rides",
    siteUrl: "https://luxyrides.ca",
    defaultTitle: "Luxy Rides - Premium Chauffeur Rides Across Canada",
    defaultDescription:
      "Premium chauffeur services for airport transfers, corporate travel, city tours, and special occasions.",
    defaultOgImage: "/og-image.jpg",
    favicon: "/favicon.ico",
    locale: "en_CA",
    twitterHandle: "@luxyrides",
    themeColor: "#22D3EE",
    googleVerification: "",
    structuredData: {
      type: "LocalBusiness",
      priceRange: "$$$",
      servesCuisine: null,
    },
  },
  company: {
    name: "Luxy Rides",
    tagline: "Premium Chauffeur Rides Across Canada",
    description:
      "Professional, reliable, luxurious transportation for airport transfers, corporate travel, and memorable events.",
    logo: { light: "/logo-light.svg", dark: "/logo-dark.svg", width: 160, height: 40 },
    founded: "2015",
    location: "Canada",
    address: "Canada",
    mapEmbedUrl: "https://maps.google.com/",
    phone: "(888) 881-6610",
    email: "info@urbanelitelimo.com",
    hours: [{ days: "Monday - Sunday", time: "24/7 Available" }],
    socialLinks: [
      { platform: "instagram", url: "https://instagram.com/luxyrides", icon: "Instagram" },
      { platform: "facebook", url: "https://facebook.com/luxyrides", icon: "Facebook" },
      { platform: "twitter", url: "https://twitter.com/luxyrides", icon: "Twitter" },
      { platform: "linkedin", url: "https://linkedin.com/company/luxyrides", icon: "Linkedin" },
    ] satisfies SocialLink[],
    stats: [
      { label: "Trips Completed", value: "12,000+", icon: "Car" },
      { label: "Professional Drivers", value: "50+", icon: "UserCheck" },
      { label: "Always Available", value: "24/7", icon: "Clock" },
      { label: "Satisfaction Rate", value: "4.9", icon: "Star" },
    ] satisfies Stat[],
    trustBadges: ["Licensed & Insured", "Professional Drivers", "24/7 Support"],
    mediaLogos: [
      { name: "Ray-Ban", logo: "Ray-Ban" },
      { name: "Politico", logo: "POLITICO" },
      { name: "Verizon", logo: "Verizon" },
      { name: "Thomson Reuters", logo: "Reuters" },
      { name: "Forbes Travel", logo: "Forbes" },
    ],
  },
  theme: {
    defaultMode: "dark",
    allowToggle: false,
    colors: {
      background: "#0A0F1A",
      surface: "#111827",
      surfaceLight: "#1F2937",
      primary: "#0369A1",
      primaryLight: "#0EA5E9",
      accent: "#22D3EE",
      accentGlow: "rgba(34, 211, 238, 0.18)",
      whiteBg: "#F8FAFC",
      textPrimary: "#FFFFFF",
      textDark: "#0F172A",
      textMuted: "#94A3B8",
      borderGlass: "rgba(255, 255, 255, 0.10)",
      borderDark: "rgba(255, 255, 255, 0.06)",
      gradientCta: "linear-gradient(90deg, #0369A1, #22D3EE)",
      gradientHero: "linear-gradient(135deg, #0c1929, #060D18, #0A0F1A)",
      success: "#10B981",
      error: "#EF4444",
      bookingWidgetBg: "rgba(10, 15, 26, 0.92)",
    },
    fonts: {
      heading: "var(--font-work-sans)",
      body: "var(--font-work-sans)",
      mono: "var(--font-fira-code)",
    },
    radii: { card: "1rem", button: "0.5rem", pill: "9999px" },
    blur: { glass: "20px", heavy: "40px" },
  },
  animations: {
    enabled: true,
    reducedMotionRespect: true,
    pageTransition: "fade-slide",
    scrollReveal: { enabled: true, defaultDelay: 0, staggerChildren: 0.1, duration: 0.65, yOffset: 30 },
    cursor: { custom: false, color: "#22D3EE", magneticElements: ["a", "button", ".magnetic"] },
  },
  navigation: {
    sticky: true,
    transparent: true,
    scrollThreshold: 80,
    links: [
      { label: "Services", href: "/services", pageKey: "services" },
      { label: "Our Fleet", href: "/fleet", pageKey: "fleet" },
      { label: "Events", href: "/events", pageKey: "events" },
      { label: "Calendar Fare", href: "/calendar-fare", pageKey: "calendar-fare" },
      { label: "Join our Team", href: "/join-team", pageKey: "join-team" },
    ] satisfies NavLink[],
    cta: { label: "Book Now", href: "/contact", variant: "gradient" },
    topBar: {
      show: true,
      message: "FPN partner deal is closing - book your airport transfers across Canada while availability lasts.",
      cta: { label: "Explore Services", href: "/services" },
    },
  },
  hero: {
    layout: "split-with-booking-widget",
    badge: { show: false },
    headline: { line1: "Premium Chauffeur", line2: "Rides Across Canada", highlightWord: "Canada" },
    subheadline:
      "Premium chauffeur services for airport transfers, corporate travel, and special occasions. Professional, reliable, luxurious.",
    backgroundImage: {
      src: "https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=2200&q=85",
      alt: "Black luxury chauffeur vehicle in a downtown setting",
    },
    overlayGradient: "linear-gradient(to right, rgba(10,15,26,0.94) 35%, rgba(10,15,26,0.42) 100%)",
    trustPills: [
      { icon: "Shield", label: "Licensed & Insured" },
      { icon: "UserCheck", label: "Professional Drivers" },
      { icon: "Clock", label: "24/7 Support" },
    ] satisfies TrustPill[],
    scrollIndicator: false,
  },
  bookingWidget: {
    title: "Book Your Ride",
    subtitle: "Reserve your premium chauffeur",
    tabs: [
      { id: "one-way", label: "One Way", icon: "ArrowRight" },
      { id: "round-trip", label: "Round Trip", icon: "Repeat2" },
      { id: "hourly", label: "Hourly", icon: "Clock" },
    ] satisfies BookingTab[],
    fields: [
      {
        name: "tripType",
        label: "Trip Type",
        type: "select",
        required: true,
        options: ["Airport Transfer", "Corporate", "Events", "Hourly Charter"],
      },
      {
        name: "pickupAddress",
        label: "Pickup Location",
        type: "location-autocomplete",
        required: true,
        placeholder: "Enter pickup location",
      },
      {
        name: "dropoffAddress",
        label: "Drop-off Location",
        type: "location-autocomplete",
        required: true,
        placeholder: "Enter destination",
      },
      { name: "pickupDate", label: "Date", type: "date", required: true },
      { name: "pickupTime", label: "Time", type: "time", required: true },
      { name: "passengers", label: "Passengers", type: "number", required: true, min: 1, max: 14 },
      { name: "luggage", label: "Luggage", type: "number", required: false, min: 0 },
    ] satisfies BookingField[],
    submitLabel: "Get Instant Quote",
    appearance: {
      position: "right",
      width: "380px",
      background: "rgba(10, 15, 26, 0.92)",
      backdropBlur: "20px",
      borderColor: "rgba(255, 255, 255, 0.10)",
    },
    paymentNote: "All payment methods accepted",
    freeCancel: "Free cancellation",
    instantConfirm: "Instant confirmation",
  },
  services: {
    page: {
      title: "Our Services",
      subtitle: "What We Offer",
      description:
        "From airport pickups to city tours, Luxy Rides provides premium transportation for the moments that require certainty.",
    },
    items: [
      {
        id: "airport-transfer",
        icon: "Plane",
        title: "Airport Transfers",
        shortDesc: "Flight-aware pickups and drop-offs at major Canadian airports.",
        fullDesc: "Meet-and-greet service, flight tracking, and wait time coverage for international arrivals.",
        price: "From $45",
        badge: "Most Popular",
        image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80",
        featured: true,
        href: "/services/airport-transfer",
        color: "#22D3EE",
      },
      {
        id: "corporate-travel",
        icon: "Briefcase",
        title: "Corporate Travel",
        shortDesc: "Discreet executive transport with reliable account support.",
        fullDesc: "Monthly billing, consistent chauffeurs, privacy-aware operations, and priority dispatch.",
        price: "Custom Rates",
        badge: "Business",
        image: cityImage,
        featured: true,
        href: "/services/corporate-travel",
        color: "#0EA5E9",
      },
      {
        id: "special-occasions",
        icon: "Sparkles",
        title: "Special Occasions",
        shortDesc: "Weddings, galas, proms, and milestone celebrations in style.",
        fullDesc: "Decorated vehicles, flexible scheduling, and polished arrivals for your most visible days.",
        price: "From $120",
        badge: null,
        image: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80",
        featured: true,
        href: "/services/special-occasions",
        color: "#8B5CF6",
      },
      {
        id: "city-tours",
        icon: "MapPin",
        title: "City Tours",
        shortDesc: "Curated city itineraries with an expert chauffeur.",
        fullDesc: "Flexible hourly service, local guidance, and elegant point-to-point travel.",
        price: "From $85/hr",
        badge: null,
        image: "https://images.unsplash.com/photo-1517935706615-2717063c2225?auto=format&fit=crop&w=1200&q=80",
        featured: false,
        href: "/services/city-tours",
        color: "#10B981",
      },
    ] satisfies ServiceItem[],
  },
  howItWorks: {
    heading: "How It Works",
    highlightWord: "Works",
    subheading: "Three simple steps to experience premium travel tailored to your schedule.",
    steps: [
      {
        step: 1,
        title: "Enter Your Trip Details",
        description: "Tell us your pickup, destination, date, and service preference.",
        icon: "MapPin",
      },
      {
        step: 2,
        title: "Get Your Quote & Confirm",
        description: "Review your instant quote, select your vehicle, and confirm securely.",
        icon: "CreditCard",
      },
      {
        step: 3,
        title: "Your Chauffeur Arrives On Time",
        description: "A professionally dressed chauffeur arrives ready for a seamless trip.",
        icon: "UserCheck",
      },
    ] satisfies HowItWorksStep[],
    mobileAppMockup: {
      show: true,
      image: "",
      alt: "Luxy Rides trip details screen",
      sampleTrip: {
        pickup: "Toronto Pearson International",
        destination: "Downtown Toronto",
        dateTime: "June 24, 2026 - 10:00 AM",
        vehicle: "Executive Sedan",
        estimatedFare: "$85.00",
        fareNote: "Includes taxes and fees",
        ctaLabel: "Get Quote",
      },
    },
    layout: "accordion-with-mockup",
  },
  fleet: {
    page: { title: "Our Fleet", highlightWord: "Fleet", subtitle: "Premium vehicles for every occasion." },
    categories: [
      { id: "sedan", label: "Sedan" },
      { id: "suv", label: "SUV" },
      { id: "sprinter", label: "Sprinter Van" },
      { id: "limousine", label: "Limousine" },
      { id: "bus", label: "Buses" },
    ] satisfies FleetCategory[],
    vehicles: [
      {
        id: "economy-sedan",
        category: "sedan",
        tier: "Budget Friendly",
        name: "Economy Sedan",
        makes: ["Camry | Corolla"],
        makeIcons: ["CircleDot"],
        passengers: 3,
        luggage: "2 suitcases",
        priceFrom: "$45",
        image: vehicleImage,
        imageAlt: "Black sedan chauffeur vehicle",
        href: "/fleet/economy-sedan",
        featured: true,
      },
      {
        id: "executive-sedan",
        category: "sedan",
        tier: "Executive Choice",
        name: "Luxury Sedan",
        makes: ["Mercedes E-Class", "BMW 5 Series"],
        makeIcons: ["BadgeCheck", "BadgeCheck"],
        passengers: 3,
        luggage: "3 suitcases",
        priceFrom: "$75",
        image: vehicleImage,
        imageAlt: "Executive luxury sedan",
        href: "/fleet/executive-sedan",
        featured: true,
      },
      {
        id: "luxury-suv",
        category: "suv",
        tier: "Flagship",
        name: "Luxury SUV",
        makes: ["Cadillac Escalade", "Lincoln Navigator"],
        makeIcons: ["BadgeCheck", "BadgeCheck"],
        passengers: 6,
        luggage: "5 suitcases",
        priceFrom: "$120",
        image: suvImage,
        imageAlt: "Black luxury SUV",
        href: "/fleet/luxury-suv",
        featured: true,
      },
      {
        id: "flagship-sedan",
        category: "sedan",
        tier: "Flagship",
        name: "Luxury Sedan",
        makes: ["Benz-S-Class", "7 Series"],
        makeIcons: ["BadgeCheck", "BadgeCheck"],
        passengers: 3,
        luggage: "2-3 suitcases",
        priceFrom: "$120",
        image: "https://images.unsplash.com/photo-1556189250-72ba954cfc2b?auto=format&fit=crop&w=1200&q=80",
        imageAlt: "Black flagship luxury sedan",
        href: "/fleet/flagship-sedan",
        featured: true,
      },
      {
        id: "executive-sprinter",
        category: "sprinter",
        tier: "Group Comfort",
        name: "Executive Sprinter",
        makes: ["Mercedes Sprinter"],
        makeIcons: ["BadgeCheck"],
        passengers: 12,
        luggage: "10 suitcases",
        priceFrom: "$185",
        image: sprinterImage,
        imageAlt: "Premium sprinter van",
        href: "/fleet/executive-sprinter",
        featured: false,
      },
      {
        id: "stretch-limousine",
        category: "limousine",
        tier: "Event Ready",
        name: "Stretch Limousine",
        makes: ["Lincoln Stretch"],
        makeIcons: ["Sparkles"],
        passengers: 8,
        luggage: "4 suitcases",
        priceFrom: "$210",
        image: vehicleImage,
        imageAlt: "Stretch limousine for special occasions",
        href: "/fleet/stretch-limousine",
        featured: false,
      },
      {
        id: "executive-coach",
        category: "bus",
        tier: "Large Group",
        name: "Executive Coach",
        makes: ["Mini Coach", "Shuttle Bus"],
        makeIcons: ["Bus", "Bus"],
        passengers: 24,
        luggage: "Group storage",
        priceFrom: "$290",
        image: sprinterImage,
        imageAlt: "Executive shuttle coach",
        href: "/fleet/executive-coach",
        featured: false,
      },
      {
        id: "party-bus",
        category: "bus",
        tier: "Celebration",
        name: "Party Bus",
        makes: ["Party Bus", "Event Shuttle"],
        makeIcons: ["Bus", "Sparkles"],
        passengers: 20,
        luggage: "Event storage",
        priceFrom: "$260",
        image: sprinterImage,
        imageAlt: "Party bus for event transportation",
        href: "/fleet/party-bus",
        featured: false,
      },
    ] satisfies FleetVehicle[],
    ctaLabel: "Book Now",
    sectionBackground: "#F8FAFC",
  },
  testimonials: {
    items: [
      {
        id: "mara",
        name: "Mara Kennedy",
        role: "Corporate Travel Manager",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80",
        rating: 5,
        text: "The dispatch team is precise, the vehicles arrive immaculate, and our executives never have to chase updates.",
        service: "Corporate Travel",
        date: "May 2026",
        verified: true,
        platform: "Google",
        ridesCompleted: 58,
      },
      {
        id: "andrew",
        name: "Andrew Patel",
        role: "Event Producer",
        avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
        rating: 5,
        text: "Luxy Miles handled a complicated gala transport schedule without a single visible wrinkle.",
        service: "Special Occasions",
        date: "April 2026",
        verified: true,
        platform: "Trustpilot",
        ridesCompleted: 34,
      },
      {
        id: "celine",
        name: "Celine Moreau",
        role: "Frequent Flyer",
        avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=300&q=80",
        rating: 5,
        text: "Flight tracking saved me twice in one month. They knew about the delay before I did.",
        service: "Airport Transfer",
        date: "June 2026",
        verified: true,
        platform: "Google",
        ridesCompleted: 41,
      },
      {
        id: "james",
        name: "James Whitfield",
        role: "Finance Executive",
        avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80",
        rating: 5,
        text: "Consistent punctuality for early-morning airport runs. The chauffeurs are professional and discreet every time.",
        service: "Airport Transfer",
        date: "March 2026",
        verified: true,
        platform: "Google",
        ridesCompleted: 72,
      },
      {
        id: "sophia",
        name: "Sophia Nguyen",
        role: "Wedding Planner",
        avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80",
        rating: 5,
        text: "Coordinated six vehicles for a wedding party flawlessly. Guests commented on how smooth everything felt.",
        service: "Event Transportation",
        date: "February 2026",
        verified: true,
        platform: "Trustpilot",
        ridesCompleted: 19,
      },
      {
        id: "daniel",
        name: "Daniel Brooks",
        role: "Consultant",
        avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80",
        rating: 4,
        text: "Reliable hourly chauffeur service across Manhattan. Billing was transparent and support replied within minutes.",
        service: "Hourly Chauffeur",
        date: "January 2026",
        verified: true,
        platform: "Google",
        ridesCompleted: 26,
      },
      {
        id: "elena",
        name: "Elena Rossi",
        role: "Luxury Travel Blogger",
        avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80",
        rating: 5,
        text: "Immaculate SUVs, bottled water, and a calm ride after a long international flight. Easily my go-to in New York.",
        service: "Airport Transfer",
        date: "May 2026",
        verified: true,
        platform: "Trustpilot",
        ridesCompleted: 12,
      },
      {
        id: "marcus",
        name: "Marcus Lee",
        role: "Startup Founder",
        avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80",
        rating: 5,
        text: "Booked same-day for a investor meeting. Driver arrived early, route was efficient, and the sedan was spotless.",
        service: "Corporate Travel",
        date: "April 2026",
        verified: true,
        platform: "Google",
        ridesCompleted: 15,
      },
      {
        id: "priya",
        name: "Priya Sharma",
        role: "Physician",
        avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80",
        rating: 5,
        text: "Night shift finishes are exhausting — having a trusted car waiting makes the commute feel effortless.",
        service: "City Rides",
        date: "March 2026",
        verified: true,
        platform: "Trustpilot",
        ridesCompleted: 47,
      },
      {
        id: "oliver",
        name: "Oliver Grant",
        role: "Hotel Concierge",
        avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=300&q=80",
        rating: 5,
        text: "We refer guests regularly. Meet-and-greet at JFK is always handled with white-glove care.",
        service: "Airport Transfer",
        date: "June 2026",
        verified: true,
        platform: "Google",
        ridesCompleted: 93,
      },
    ] satisfies Testimonial[],
  },
  about: {
    page: {
      title: "Built for Discerning Travel",
      subtitle: "About Luxy Rides",
      description:
        "A chauffeur company shaped by operational discipline, hospitality, and a deep respect for time.",
    },
    story: {
      headline: "Quiet excellence, delivered ride after ride.",
      body: "Since 2015, Luxy Rides has supported executives, families, event planners, and frequent flyers with transportation that feels calm, controlled, and personal.",
      image: suvImage,
      imageAlt: "Chauffeur opening the door of a luxury vehicle",
    },
    values: [
      { icon: "Clock", title: "Punctuality", description: "Every ride is planned around precision and proactive dispatch." },
      { icon: "Shield", title: "Discretion", description: "Privacy-aware chauffeurs and secure operational standards." },
      { icon: "Sparkles", title: "Presentation", description: "Vehicles are prepared to feel polished, calm, and client-ready." },
      { icon: "Headphones", title: "Support", description: "Human support is available any time schedules change." },
    ] satisfies Value[],
    team: [
      {
        id: "nora",
        name: "Nora Ellis",
        role: "Operations Director",
        bio: "Leads dispatch standards and service recovery.",
        image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=600&q=80",
        credentials: ["12 years logistics", "Safety lead"],
        socials: { linkedin: "#" },
      },
      {
        id: "marcus",
        name: "Marcus Chen",
        role: "Fleet Manager",
        bio: "Oversees vehicle care, inspections, and presentation.",
        image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80",
        credentials: ["Fleet certified", "Luxury detailing"],
        socials: { linkedin: "#" },
      },
      {
        id: "amina",
        name: "Amina Walker",
        role: "Client Concierge",
        bio: "Coordinates VIP itineraries and event movement plans.",
        image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80",
        credentials: ["VIP service", "Event logistics"],
        socials: { linkedin: "#" },
      },
    ] satisfies TeamMember[],
    certifications: [
      { name: "Licensed Operator", logo: "Licensed Operator" },
      { name: "Commercially Insured", logo: "Commercially Insured" },
      { name: "Airport Authorized", logo: "Airport Authorized" },
      { name: "Safety Audited", logo: "Safety Audited" },
    ] satisfies Certification[],
  },
  contact: {
    page: {
      title: "Request a Quote",
      subtitle: "Contact",
      description: "Tell us where you are going. A concierge confirms your ride details within 30 minutes.",
    },
    layout: "split-form",
    form: {
      fields: [
        { name: "name", label: "Full Name", type: "text", required: true, placeholder: "Your name" },
        { name: "email", label: "Email", type: "email", required: true, placeholder: "you@example.com" },
        { name: "phone", label: "Phone", type: "tel", required: true, placeholder: "+1 555 000 0000" },
        {
          name: "service",
          label: "Service",
          type: "select",
          required: true,
          placeholder: "Choose a service",
          options: ["Airport Transfer", "Corporate Travel", "Special Occasion", "Hourly Charter"],
        },
        { name: "date", label: "Date", type: "date", required: true, placeholder: "Select date" },
        { name: "time", label: "Time", type: "time", required: true, placeholder: "Select time" },
        { name: "passengers", label: "Passengers", type: "number", required: true, placeholder: "2" },
        { name: "message", label: "Trip Details", type: "textarea", required: false, placeholder: "Pickup, destination, luggage, and any special requests" },
      ] satisfies FormField[],
      submitLabel: "Request a Quote",
      successMessage: "Thank you. A concierge will confirm the details shortly.",
      errorMessage: "Please check your details and try again.",
      apiEndpoint: "/api/contact",
    },
    info: { showMap: false, showHours: true, showSocials: true, phoneCTA: "Need immediate assistance? Call us 24/7." },
  },
  footer: {
    layout: "4-column",
    tagline: "Premium chauffeur service with calm execution and polished vehicles.",
    columns: [
      {
        heading: "Company",
        links: [
          { label: "About", href: "/about" },
          { label: "Join our Team", href: "/join-team" },
          { label: "Contact", href: "/contact" },
        ],
      },
      {
        heading: "Services",
        links: [
          { label: "Airport Transfers", href: "/services/airport-transfer" },
          { label: "Corporate Travel", href: "/services/corporate-travel" },
          { label: "Events", href: "/events" },
        ],
      },
      {
        heading: "Explore",
        links: [
          { label: "Fleet", href: "/fleet" },
          { label: "Calendar Fare", href: "/calendar-fare" },
          { label: "Services", href: "/services" },
        ],
      },
    ] satisfies FooterColumn[],
    newsletter: { show: false },
    bottomBar: {
      copyright: "© 2025 Urban Elite Limo. All Rights Reserved",
      links: [
        { label: "Privacy", href: "/privacy" },
        { label: "Terms", href: "/terms" },
      ],
    },
  },
  globalComponents: {
    bookingCTABanner: { show: true, text: "Ready for a smoother arrival?", cta: { label: "Book Now", href: "/contact" } },
    phoneFAB: { show: true, number: "+18888816610", label: "Call 24/7" },
    cookieBanner: { show: true, message: "We use cookies to improve booking performance.", acceptLabel: "Accept", declineLabel: "Decline" },
    chatWidget: { show: false, provider: "", widgetId: "" },
  },
} as const;

export const theme = SITE_CONFIG.theme;
export const colors = theme.colors;

export function getGradient(type: "hero" | "cta" | "primary" | "accent") {
  if (type === "hero") return colors.gradientHero;
  if (type === "cta") return colors.gradientCta;
  if (type === "primary") return `linear-gradient(135deg, ${colors.primary}, ${colors.primaryLight})`;
  return `linear-gradient(135deg, ${colors.accent}, ${colors.primaryLight})`;
}

export function getThemeColor(colorKey: keyof typeof colors) {
  return colors[colorKey];
}

export function getAccentWithAlpha(alpha: number) {
  return `rgba(34, 211, 238, ${alpha})`;
}

export function getPrimaryWithAlpha(alpha: number) {
  return `rgba(3, 105, 161, ${alpha})`;
}

export function getGlowEffect(type: "primary" | "accent" | "soft") {
  if (type === "accent") return `0 0 40px ${colors.accentGlow}`;
  if (type === "primary") return `0 0 40px rgba(14, 165, 233, 0.22)`;
  return "0 18px 80px rgba(0,0,0,0.34)";
}

export * from "./content";
